### Inscription
POST http://localhost:3000/api/v1/inscription
Content-Type: application/json

{
  "nom": "Test",
  "prenom": "User",
  "email": "testuser@email.com",
  "motDePasse": "password123"
}

### Connexion
POST http://localhost:3000/api/v1/connexion
Content-Type: application/json

{
  "email": "abdelhakimbaalla50@gmail.com",
  "motDePasse": "123456789"
}

### Mot de passe oublié
POST http://localhost:3000/api/v1/forget-password
Content-Type: application/json

{
  "email": "abdelhakimbaalla50@gmail.com"
}

### Réinitialisation du mot de passe
POST http://localhost:3000/api/v1/reset-password/token
Content-Type: application/json

{
  "motDePasse": "nouveaumdp123"
}

### Création d'utilisateur par admin
POST http://localhost:3000/api/v1/utilisateurs/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZWQ0NWM0YmVkYmZlMmRkMDJkMzQwNiIsInJvbGUiOiI2OGVkMzk3NDllNDhjNTc5ODMyMjYzMjciLCJpYXQiOjE3NjA5NDg3MDksImV4cCI6MTc2MDk0OTYwOX0.cAF9M98AdYLrSekVZXS0aC0w1cChINws4IozYTKHoUk

{
  "nom": "Medecin",
  "prenom": "Test",
  "email": "medecin2@email.com",
  "motDePasse": "password123",
  "role": "medecin"
}
