@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZWQ0NWM0YmVkYmZlMmRkMDJkMzQwNiIsInJvbGUiOiI2OGVkMzk3NDllNDhjNTc5ODMyMjYzMjciLCJpYXQiOjE3NjA5NTYxMjgsImV4cCI6MTc2MDk1NzAyOH0.b-ekl7vD7jFpvJGJPs1u11PIBIbb8UznRI-Vjz1cpmY
@patientId = 68f60fcd0cca05382a89f143
### Inscription
POST http://localhost:3000/api/v1/inscription
Content-Type: application/json

{
    "nom": "Test",
    "prenom": "User",
    "email": "testuser@email.com",
    "motDePasse": "password123"
}

### Connexion
POST http://localhost:3000/api/v1/connexion
Content-Type: application/json

{
    "email": "abdelhakimbaalla50@gmail.com",
    "motDePasse": "123456789"
}

### Mot de passe oublié
POST http://localhost:3000/api/v1/forget-password
Content-Type: application/json

{
    "email": "abdelhakimbaalla50@gmail.com"
}

### Réinitialisation du mot de passe
POST http://localhost:3000/api/v1/reset-password/token
Content-Type: application/json

{
    "motDePasse": "nouveaumdp123"
}

### Création d'utilisateur par admin
POST http://localhost:3000/api/v1/utilisateurs/create
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "nom": "Patient",
    "prenom": "Test",
    "email": "patient@email.com",
    "motDePasse": "password123",
    "role": "patient"
}

### Suspendre un utilisateur
PUT http://localhost:3000/api/v1/utilisateurs/68ee2cc6c0ab57987a0c8f62/suspend
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### Réactiver un utilisateur
PUT http://localhost:3000/api/v1/utilisateurs/68ee2cc6c0ab57987a0c8f62/reactive
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### Création d'un patient
POST http://localhost:3000/api/v1/patients
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "nom": "Ali",
    "prenom": "Ben",
    "email": "ali.ben@email.com",
    "sexe": "Homme"
}

### Liste des patients
GET http://localhost:3000/api/v1/patients
Authorization: Bearer {{adminToken}}

### Recherche patient par nom
GET http://localhost:3000/api/v1/patients?nom=Ali
Authorization: Bearer {{adminToken}}

### Récupérer un patient par ID
GET http://localhost:3000/api/v1/patients/{{patientId}}
Authorization: Bearer {{adminToken}}

### Modifier un patient
PUT http://localhost:3000/api/v1/patients/{{patientId}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "nom": "AliModif",
    "prenom": "BenModif"
}

### Supprimer un patient
DELETE http://localhost:3000/api/v1/patients/{{patientId}}
Authorization: Bearer {{adminToken}}
